/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package test;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;

/**
 *
 * @author Curiale Alessandro
 */
public class GameMenu extends javax.swing.JPanel {

    /**
     * Creates new form GameMuni
     */
    public GameMenu() {
        initComponents();
        this.setSize(1920, 1080);
    }
    
    private void raiseChange(String eventType){
        PropertyChangeEvent event = new PropertyChangeEvent(this, eventType, -1, 1);
        PropertyChangeListener[] listeners = this.getPropertyChangeListeners();
        synchronized (listeners){
            for (PropertyChangeListener e : listeners){
                e.propertyChange(event);
            }
        }
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playWithTime = new javax.swing.JButton();
        playWithPoints = new javax.swing.JButton();
        testCamButton = new javax.swing.JButton();
        listCamButton = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(2, 1));

        playWithTime.setBackground(new java.awt.Color(0, 102, 51));
        playWithTime.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        playWithTime.setText("Gioca a tempo");
        playWithTime.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(103, 62, 2)));
        playWithTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playWithTimeActionPerformed(evt);
            }
        });
        add(playWithTime);

        playWithPoints.setBackground(new java.awt.Color(0, 102, 51));
        playWithPoints.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        playWithPoints.setText("Gioca a punti");
        playWithPoints.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(103, 62, 2)));
        playWithPoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playWithPointsActionPerformed(evt);
            }
        });
        add(playWithPoints);

        testCamButton.setText("Test WebCam");
        testCamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testCamButtonActionPerformed(evt);
            }
        });
        add(testCamButton);

        listCamButton.setText("ListDeviceWebCam");
        listCamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listCamButtonActionPerformed(evt);
            }
        });
        add(listCamButton);
    }// </editor-fold>//GEN-END:initComponents

    private void playWithPointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playWithPointsActionPerformed
        raiseChange("playP");
    }//GEN-LAST:event_playWithPointsActionPerformed

    private void testCamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testCamButtonActionPerformed
        raiseChange("capture");
    }//GEN-LAST:event_testCamButtonActionPerformed

    private void listCamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listCamButtonActionPerformed
        raiseChange("list");
    }//GEN-LAST:event_listCamButtonActionPerformed

    private void playWithTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playWithTimeActionPerformed
        raiseChange("playT");
    }//GEN-LAST:event_playWithTimeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton listCamButton;
    private javax.swing.JButton playWithPoints;
    private javax.swing.JButton playWithTime;
    private javax.swing.JButton testCamButton;
    // End of variables declaration//GEN-END:variables
}
