/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package test;

import java.awt.Color;
import javax.swing.ButtonGroup;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import org.bytedeco.videoinput.videoInput;

/**
 *
 * @author Curiale Alessandro
 */
public class SettingsPanel extends javax.swing.JPanel {

    /**
     * Creates new form SettingsPanel
     */
    private final int DEFAULT_WEBCAM = 0;
    
    public SettingsPanel() {
        //initComponents();
        this.setSize(1920, 1080);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout(0, 1));
    }// </editor-fold>//GEN-END:initComponents

    public void createList() {
        
        
        int count = (int)videoInput.listDevices();
        
        String[] descriptions = new String[count];
        
        ButtonGroup group = new ButtonGroup();
        JRadioButton btn = null;
        
        for (int i = 0; i < descriptions.length; i++) {
            descriptions[i] = videoInput.getDeviceName(i).getString();
        }  
        for (int i = 0; i < descriptions.length; i++) {
            System.out.println("");
            if(i == 0){
                btn = new JRadioButton(i + ") " + descriptions[i]);btn.setSelected(true);
            }else{
                btn = new JRadioButton(i + ") " + descriptions[i]);
            }
            group.add(btn);
            this.add(btn);
        }
        initComponents();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
