/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fruit.ninja.webcam.v2;

import de.gurkenlabs.litiengine.Game;
import de.gurkenlabs.litiengine.input.Input;
import de.gurkenlabs.litiengine.resources.Resources;
import de.gurkenlabs.litiengine.*;
import de.gurkenlabs.litiengine.GameWindow;

public class Main {
    
    public static void main(String[] args) {
        
        Game.info().setName("FRUIT NINJA WEBCAM");
        Game.info().setSubTitle("");
        Game.info().setVersion("v0");
        Game.info().setDescription("Una prova di un gioco in litiengine");

        Game.window.setResolutionHeight(34);

        Game.init(args);

        
        //Resources.load("app/src/main/resources/game.litidata");

        Game.start();
    }


}
